// userReducerAction =================
export const SET_USER = "SET_USER";
export const GET_USER = "GET_USER"; //used with saga
export const UPDATE_USER = "UPDATE_USER"; //used with saga
export const UNSET_USER = "UNSET_USER"; // for logging out purpose
export const REGISTER_USER = "REGISTER_USER"; // used in saga
export const SET_LOADING_USER = "SET_LOADING_USER";
export const UNSET_LOADING_USER = "UNSET_LOADING_USER";
export const SIGN_IN_USER = "SIGN_IN_USER"; // used in saga
export const OPEN_LOGIN_INFO_MODAL = "OPEN_LOGIN_INFO_MODAL";
export const CLOSE_LOGIN_INFO_MODAL = "CLOSE_LOGIN_INFO_MODAL";
export const OPEN_REGISTER_INFO_MODAL = "OPEN_REGISTER_INFO_MODAL";
export const CLOSE_REGISTER_INFO_MODAL = "CLOSE_REGISTER_INFO_MODAL";

// modal Reducer ====================
export const OPEN_MODAL_AUTH = "OPEN_MODAL_AUTH";
export const CLOSE_MODAL_AUTH = "CLOSE_MODAL_AUTH";
export const OPEN_CREATE_PLAYLIST_MODAL = "OPEN_CREATE_PLAYLIST_MODAL";
export const CLOSE_CREATE_PLAYLIST_MODAL = "CLOSE_CREATE_PLAYLIST_MODAL";

//userPlaylistReducer =================
export const GET_USER_PLAYLIST = "GET_USER_PLAYLIST"; //USED BY SAGA
export const SET_USER_PLAYLIST = "SET_USER_PLAYLIST";
export const SET_LOADING_USER_PLAYLIST = "SET_LOADING_USER_PLAYLIST";
export const UNSET_LOADING_USER_PLAYLIST = "UNSET_LOADING_USER_PLAYLIST";
export const SET_FAILED_INFO_USER_PLAYLIST = "SET_FAILED_INFO_USER_PLAYLIST";
export const SET_SUCCESS_INFO_USER_PLAYLIST = "SET_SUCCESS_INFO_USER_PLAYLIST";
export const UNSET_INFO_USER_PLAYLIST = "UNSET_INFO_USER_PLAYLIST" 

//playlistDetailReducer =====================
export const GET_PLAYLIST_DETAIL = "GET_PLAYLIST_DETAIL";
export const SET_PLAYLIST_DETAIL = "SET_PLAYLIST_DETAIL";
export const SET_LOADING_PLAYLIST_DETAIL = "SET_LOADING_PLAYLIST_DETAIL";
export const UNSET_LOADING_PLAYLIST_DETAIL = "UNSET_LOADING_PLAYLIST_DETAIL";
export const RESET_PLAYLIST_DETAIL = "RESET_PLAYLIST_DETAIL"; 
